# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    - { resource: parameters.yml }
services:

    iko_exchange.driver.olap:
        class: xeops\iikoExchangeBundle\Driver\iikoOlapDriver
        arguments: ["@logger", "@iiko_exchange.provider"]
    iiko_exchange.conection:
        class: iiko\Connection\iikoConnection
        arguments: ["@logger"]
        calls:
            -[setServer, ['%exchanger_server%']]
            -[setUserName, ['%exchanger_user%]]
            -[setPasswordHash,['%exchanger_password_hash%]]

    iiko_exchange.provider:
        class: iiko\Connection\Provider
        arguments: ['@logger', '@iiko_exchange.conection']